services:
  - type: web
    name: ranum-backend-server
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend-server.py"
